name: h_ref
description: A divine encyclopedia of ancient and modern deities with full CRUD functionality.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  uuid: ^4.3.3
  google_fonts: ^6.1.0
  flutter_staggered_animations: ^1.1.1
  flutter_slidable: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  image_path: "assets/black-card-heart.png"
